name: åŒæ­¥ä¸Šæ¸¸ä»“åº“

env:
  SERVERCHAN_SCKEY: true

permissions:
  contents: write

on:
  schedule:
    - cron: "0 16 * * 0" # åŒ—äº¬æ—¶é—´æ¯å‘¨ä¸€ 0:00 AM è‡ªåŠ¨è¿è¡Œ
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      # Step 1: run a standard checkout action
      - name: æŸ¥çœ‹ç›®æ ‡ä»“åº“
        uses: actions/checkout@main

      # Step 2: run the sync action
      - name: åŒæ­¥ä¸Šæ¸¸æ›´æ–°
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@main
        with:
          upstream_sync_repo: kenzok8/small-package # ä¸Šæ¸¸ä»“åº“è·¯å¾„
          upstream_sync_branch: main # ä¸Šæ¸¸ä»“åº“åˆ†æ”¯
          target_sync_branch: main # ç›®æ ‡ä»“åº“åˆ†æ”¯
          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # ç›®æ ‡ä»“åº“ä»¤ç‰Œ(è‡ªåŠ¨ç”Ÿæˆï¼Œæ— éœ€è®¾ç½®)

          # Set test_mode true to run tests instead of the true action!!
          test_mode: false

      - name: æ£€æŸ¥åŒæ­¥çŠ¶æ€
        if: failure()
        run: |
          echo "[Error] ç”±äºä¸Šæ¸¸ä»“åº“çš„ workflow æ–‡ä»¶å˜æ›´ï¼Œå¯¼è‡´ GitHub è‡ªåŠ¨æš‚åœäº†æœ¬æ¬¡è‡ªåŠ¨æ›´æ–°ï¼Œä½ éœ€è¦æ‰‹åŠ¨ Sync Fork ä¸€æ¬¡"
          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
          exit 1

      - name: å‘é€é€šçŸ¥
        if: env.SERVERCHAN_SCKEY == 'true'
        run: |
          curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=æˆ‘äº²çˆ±çš„âœ¨ä¸»äººâœ¨jiemei0754ï¼šæ‚¨åŒæ­¥OpenWrt_small-packageä¸Šæ¸¸ä»“åº“é¡ºåˆ©å®Œæˆäº†ï¼ğŸ’" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
